# Generated by Django 2.0.5 on 2018-06-07 19:42

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VozniRed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrijemePol', models.TimeField(verbose_name='vrijeme polaska')),
                ('vrijemeDol', models.TimeField(verbose_name='vrijeme dolaska')),
                ('datum', models.DateField()),
                ('brojKar', models.PositiveSmallIntegerField(verbose_name='broj dostupnih karata')),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            managers=[
                ('voznired', django.db.models.manager.Manager()),
            ],
        ),
    ]
