# Generated by Django 2.0.5 on 2018-06-11 14:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sustav', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KupljeneKarte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korIme', models.CharField(max_length=30, verbose_name='korisničko ime')),
                ('brKartice', models.BigIntegerField(verbose_name='broj kreditne kartice')),
                ('datum', models.DateField()),
                ('vrijemePol', models.TimeField(verbose_name='vrijeme polaska')),
                ('vrijemeDol', models.TimeField(verbose_name='vrijeme dolaska')),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            managers=[
                ('kupkarte', django.db.models.manager.Manager()),
            ],
        ),
    ]
