# Generated by Django 2.0.5 on 2018-06-13 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustav', '0002_kupljenekarte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kupljenekarte',
            name='brKartice',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999999999)], verbose_name='broj kreditne kartice'),
        ),
    ]
