# Generated by Django 2.0.5 on 2018-06-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustav', '0003_auto_20180613_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kupljenekarte',
            name='brKartice',
            field=models.BigIntegerField(verbose_name='broj kreditne kartice'),
        ),
    ]
