# Generated by Django 2.0.6 on 2018-06-07 12:55

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('registracija', '0004_auto_20180605_2123'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='podaci',
            managers=[
                ('korisnici', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='podaci',
            name='posBr',
            field=models.BigIntegerField(null=True, verbose_name='poštanski broj'),
        ),
    ]
