# Generated by Django 2.0.5 on 2018-06-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registracija', '0005_auto_20180607_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podaci',
            name='posBr',
            field=models.PositiveIntegerField(null=True, verbose_name='poštanski broj'),
        ),
    ]
