# Generated by Django 2.0.5 on 2018-06-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registracija', '0008_auto_20180607_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podaci',
            name='brKartice',
            field=models.BigIntegerField(verbose_name='broj kreditne kartice'),
        ),
    ]
